component differential "kinematics for a differential transmission";

pin in float roll "rotation around one axis (in degrees)";
pin in float pitch "rotation around the other axis (in degrees)";

pin out float motor0 "commanded position of motor0 (based on roll & pitch inputs)";
pin out float motor1 "commanded position of motor1 (based on roll & pitch inputs)";

function _;
license "GPL";

;;

FUNCTION(_) {
    motor0 = roll + pitch;
    motor1 = roll - pitch;
}
